### ISSUE TITLE
🚨 Error on build with version 2.2.2

### ISSUE THREAD

**Issue by lschaeffer313** [ja2375/add_2_calendar#121]
## Problem
When building the application with the version 2.2.2, i encountered an error which said that it got an unresolved reference : LOCATION.
I tested with the version 2.2.1 and no error.

Screenshot of the error :
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/28922072/204116902-ba1c148e-5530-4344-982b-d3a96c6f1d93.png">

Also happened when building on GitHub Action :
<img width="980" alt="image" src="https://user-images.githubusercontent.com/28922072/204116966-aeac2167-8bed-4898-9b45-89e6e25d60d9.png">

Thank you for your action.

**Comment by diegog-sf** [comment]
Thanks for reporting this, I'll have a look!

**Comment by Inventrohyder** [comment]
It seems to be caused by the PR #120 

I am getting the same error

```
e: ~/add_2_calendar/android/src/main/kotlin/com/javih/add_2_calendar/Add2CalendarPlugin.kt: (101, 53): Unresolved reference: LOCATION

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':add_2_calendar:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Comment by wryczko** [comment]
I am experiencing the same issue

**Comment by lschaeffer313** [comment]
It was resolved in 2.2.3.
Thank you for your action.
